version: '3'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/api
      - static:/api/static/
      - media:/api/media/
    environment:
      - DATABASE_HOST=database
    env_file:
      - .env

  bot:
    build: ./bot
    depends_on:
      - api
    volumes:
      - .:/app
    environment:
      - API_HOST=http://api:8000/
    env_file:
      - .env

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18960707
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  nginx: 
    build: ./nginx
    depends_on:
      - api
    volumes:
      - static:/api/static/
      - media:/api/media/
    ports:
      - 80:80

volumes:
  database-data:
  static:
  media: